version: '3'

services:
  elgen-esg-model-service:
    build:
      context: ../elgen-esg-model-service/
    restart: always
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8003
      MODEL_NAME: "gpt2"
      # database config
      MODEL_DIRECTORY: models/
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_MODEL_NAME: "gpt-3.5-turbo"
      MODEL_TYPE: 'OPENAI'
      LOAD_LOCAL_MODEL: 0
      MODEL_MAX_LENGTH: 50
      MODEL_DEVICE_MAP: 'auto'
      TOPIC_CLASSIFIER_MODEL_NAME: 'cardiffnlp/tweet-topic-21-multi'
    container_name: elgen-esg-model-service
    ports:
      - "5943:8003"
    volumes:
      - /docker_volumes/elgen/artifacts/models/:/app/models/
