from pydantic import BaseModel, Field


class ModelAnswer(BaseModel):
    response: str = Field(..., description="Answer generated by the model.")
    prompt_length: int | None = Field(default=None, description="Total prompt length in terms of tokens.")
    inference_time: float = Field(..., description="Inference time in terms of seconds.")
    model_name: str = Field(..., description="the exact model name that produced this answer")
